#!/bin/bash

set -e

while true; do
    echo "Make your choice"
    select choice in "Create a new sink" "Route audio" "Delete a route" "Delete a sink" "Quit"; do
        case $choice in
            "Create a new sink")
                read -p "Sink name? " name
                pactl load-module module-null-sink sink_name="$name" sink_properties=device.description="$name"
                break
                ;;

            "Delete a route")
                declare -A routes
                while read line; do
                    id=$(echo $line | awk '{print $1}')
                    src=$(echo $line | awk '{print $3}' | cut -d= -f2)
                    dst=$(echo $line | awk '{print $4}' | cut -d= -f2)
                    routes["$id: ${src} -> ${dst}"]="$id"
                done < <(pactl list short modules | grep module-loopback)

                echo "Select route:"
                select route in "${!routes[@]}"; do
                    break
                done
                echo

                pactl unload-module ${routes[$route]}

                unset routes

                break
                ;;

            "Delete a sink")
                declare -A sinks
                while read line; do
                    name=$(echo $line | awk '{print $3}' | cut -d= -f2)
                    id=$(echo $line | awk '{print $1}')
                    sinks["$id: $name"]="$id"
                done < <(pactl list short modules | grep module-null-sink)

                echo "Select sink:"
                select sink in "${!sinks[@]}"; do
                    break
                done
                echo

                pactl unload-module ${sinks[$sink]}

                unset sinks

                break
                ;;

            "Route audio")
                echo "Select an input:"
                select source in $(pactl list short sources | awk '{print $2}'); do
                    break
                done
                echo

                echo "Select an output:"
                select sink in $(pactl list short sinks | awk '{print $2}'); do
                    break
                done
                echo

                pactl load-module module-loopback source=$source sink=$sink

                break
                ;;
            *)
                exit
                ;;
        esac
    done
done
